name: "JDMA data retrieving"
description: "Récupération des données JDMA pour une démarche"

inputs:
  id:
    description: "ID of the procedure"
    required: true
  startDate:
    description: "Get data from this date"
    required: true
  endDate:
    description: "Get data to this date"
    required: false
  output:
    description: "Path to output file. defaults to jdma.json"
    default: "jdma.json"
    required: true
  output2:
    description: "Path to output file. defaults to jdma2.json"
    default: "jdma2.json"
    required: false

runs:
  using: "composite"
  steps:
    - name: Install
      shell: bash
      run: |
        cd ${{ github.action_path }}
        yarn
    - name: JDMA retrieve data
      shell: bash
      run: |
        cd ${{ github.action_path }}
        node index ${{ inputs.id }} ${{ inputs.startDate }} ${{ inputs.endDate }} false > ${{ github.workspace }}/${{ inputs.output }}
        cat ${{ github.workspace }}/${{ inputs.output }}
    - name: JDMA retrieve last 3 months data
      shell: bash
      run: |
        cd ${{ github.action_path }}
        node index ${{ inputs.id }} ${{ inputs.startDate }} ${{ inputs.endDate }} true > ${{ github.workspace }}/${{ inputs.output2 }}
        cat ${{ github.workspace }}/${{ inputs.output2 }}

