name: 'Get Airtable procedures URLs to scan'
description: 'Rapatrier les URLs des démarches via Airtable pour préparer le scan'

inputs:
  id:
    description: 'ID of the procedure'
    required: true
  airtable_api_key:
    description: 'Clé API Airtable'
    required: true
  airtable_base_id:
    description: 'Identifiant de la base Airtable'
    required: true
  airtable_table_name:
    description: 'Nom de la table Airtable'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Install jq for json parsing
      shell: bash
      run: sudo apt-get install -y jq
    - id: airtable_urls
      name: Insert Airtable data
      shell: bash
      run: |
        CURRENT_DATE=$(date +"%d-%m-%Y")
        cd ${{ github.workspace }}/results/${{ inputs.id }}/${CURRENT_DATE}
        A11Y=$(cat declaration-a11y.json | jq -R .)
        RGAA=$(echo "{}" | jq -R .)
        if test -f "rgaa.json"; then
          RGAA=$(cat rgaa.json | jq -R .)
        fi
        JDMA=$(echo "{}" | jq -R .)
        if test -f "jdma.json"; then
          JDMA=$(cat jdma.json | jq -R .)
        fi
        cd ${{ github.action_path }}
        yarn
        node index ${{ inputs.id }} ${{ inputs.airtable_api_key }} ${{ inputs.airtable_base_id }} ${{ inputs.airtable_table_name }} "${A11Y}" "${RGAA}" "${JDMA}"
