name: "Get Airtable procedures URLs to scan"
description: "Rapatrier les URLs des démarches via Airtable pour préparer le scan"

inputs:
  id:
    description: "ID of the procedure"
    required: true

runs:
  using: "composite"
  steps:
    - name: Go to last data path
      shell: bash
      run: |
        CURRENT_DATE=$(date +"%d-%m-%Y")
        cd ${{ github.workspace }}/results/${{ inputs.id }}/$CURRENT_DATE
    - id: airtable_urls
      name: Insert Airtable data
      shell: bash
      run: |
        ls
